---
- name: Install AWSCLI
  pip: name=awscli state=present

- name: Create AWSCLI credentials
  file: path=~/.aws owner={{ ansible_env.USER }} state=directory

- name: Create template
  template: src=aws_config.j2 dest=~/.aws/config owner={{ ansible_env.USER }} backup=yes

- name: create distro config and place in tmp directory
  template: src=create-distro.json.j2 dest=/tmp/{{ item.bucket_name }}.json
  with_items:
    - "{{ asset_vars }}"

- name: create Cloudfront distributions
  command: "aws cloudfront create-distribution --distribution-config=file:///tmp/{{ item.bucket_name }}.json --profile {{ app_name }}"
  with_items:
    - "{{ asset_vars }}"

- name: List Cloudfront distrinutions
  shell: "aws cloudfront list-distributions --profile {{ app_name }} | grep DomainName"
  register: cloudfront_results

- debug: var=cloudfront_results

